from __future__ import annotations


SHOGI_RICH_POSITION_INPUT_MODULE_ID = (
    "shogi_rich_global_square_piece_line_pair_drop_shadow_coarse_counterfactual_drop_potential_position_input"
)
SHOGI_ALPHA_ZERO_LIKE_POSITION_INPUT_MODULE_ID = "shogi_alpha_zero_like_no_history_position_input"
SHOGI_DLSHOGI_LIKE_POSITION_INPUT_MODULE_ID = "shogi_dlshogi_like_position_input"
SHOGI_MINIMAL_SINGLE_GLOBAL_POSITION_INPUT_MODULE_ID = "shogi_minimal_single_global_position_input"
SHOGI_MINIMAL_SPLIT_GLOBAL_POSITION_INPUT_MODULE_ID = "shogi_minimal_split_global_position_input"
